### ISSUE TITLE
is:issue is:open You say on your site - "To use Comic Neue, simply install the OpenType (OTF) files on your system." Well, how do I do that? Do you really expect people who use CS to know what OTF is?

### ISSUE THREAD

**Issue by KOTYAR** [crozynski/comicneue#14]
By the way, thank you so much for making an alternative to that hackjob of a font

**Comment by crozynski** [comment]
Hi @KOTYAR. Font installation is different for every operating system, so I avoided going into that detail. Installing Comic Neue is no different to any other font, so if you google how to install fonts on your particular OS, you shouldn't have any trouble. Thanks
