### ISSUE TITLE
please provide build instructions

### ISSUE THREAD

**Issue by fabiangreffrath** [crozynski/comicneue#19]
You provide the font sources both in Glyphs and UFO format. While this is laudable per se, it is unclear which are the canonical sources that are to be used in order to rebuild the fonts, e.g. for redistribution in Debian.

**Comment by fabiangreffrath** [comment]
Asking again:

In Debian, we rebuild the fonts from the UFO sources that were distributed with the 2,.4 release:
https://salsa.debian.org/fonts-team/fonts-comic-neue/-/blob/master/debian/rules

Now, there is an additional "Glyphs" directory available in the sources which is 5 months younger than the respective "UFO" directory and the last commit message touching the latter reads `"Ufo files must not be tracked"` - which is quite a surprise. So, if there is any prefered way to build the font from its sources, please tell so.

**Comment by fabiangreffrath** [comment]
Why can't I get a reply here?

**Comment by crozynski** [comment]
@vv-monsalve Can you help Fabian here?

**Comment by fabiangreffrath** [comment]
The situation is even more confusing, because there is also the directory called "Files-from-UFO" in the Glyphs directory which contains glyphs-sources apparently generated from the ufo-sources for both the angular and the rounded variant, whereas the Glyphs directory itself only contains the glyphs-sources for the rounded variant. This means we have a choice of three possible sources for the fonts: UFO, Glyphs and Glyphs-from-UFO.

Additionally, there is a file called "ComicNeue-Angular_Bold_Oblique.glyphs" in the "Rounded-from-UFO" directory - which quite obviously doesn't belong there. Perfectly confusing, if you are asking me. 😕

**Comment by crozynski** [comment]
Hi @fabiangreffrath , thanks for following up. I'm committed to getting this fixed.
This is an open source, free project that has been improved by contributors like yourself.
If you were to improve the directory structure to make it clearer what the canonical source is, and better organise ancillary files, what would your preference be?
Assume the .glyphs files are the source, I'll try and confirm with @vv-monsalve 
Happy for you to suggest an example here, or fork, fix, and submit a PR.

**Comment by crozynski** [comment]
Viviana, who was contracted by Google to master the font for their library and was the last to edit the files, provided the following info:

– The latest files are in the root Glyphs files (the most recent also). This means the 'UFO' directory i the root can be archived.
– The directory 'Files from UFO' were what she exported at the beginning of the process. 
– The 'Rounded-from-UFO' directory can be archived. 
– The 'Angular-from-UFO' files are the source for the angular variant. Google chose not to add this variant to their library and no work was done to these following their export to .glyphs format. 

I would suggest renaming 'Angular-from-UFO' to 'Angular' and moving it up a level into the 'Glyphs' directory.

**Comment by fabiangreffrath** [comment]
Thanks for your reply @crozynski !

> Happy for you to suggest an example here, or fork, fix, and submit a PR.

I don't have a very specific directory layout in mind. I'd be glad if only the actual caconical sources would be available and any obsolete or redundant copies be removed.

> I would suggest renaming 'Angular-from-UFO' to 'Angular' and moving it up a level into the 'Glyphs' directory.

If all the other source copies would be removed this sounds like a sensible approach. Thanks!

**Comment by crozynski** [comment]
@fabiangreffrath Done!

**Comment by fabiangreffrath** [comment]
Great, thank you!
