### ISSUE TITLE
Non English characters do not load in Flash / ActionScript 3 text fields.

### ISSUE THREAD

**Issue by bmcilmoyle** [crozynski/comicneue#2]
![example](https://cloud.githubusercontent.com/assets/5520591/8621775/71cc4c72-26f5-11e5-9dae-b05feb2a83f1.PNG)

when attempting to use ComicNeue-Regular.ttf to display a simple sentence with Russian characters it draws blanks on any non English character. The image attached shows the results where it doesn't dispaly non English charactes/

I've narrowed it down in ActionScript 3 code to the textField.getCharBoundaries function. It tries to find the boundaries of a character and normally would return a rectangle that surrounds the character but fails too.

in the attached image I'm attempting to display: Вы были в норме - не живой - когда Pistov играл с вами.

**Comment by crozynski** [comment]
Doesn't work because Russian not supported.
