### ISSUE TITLE
Angular fonts conflict names with regular (non-angular?) ones in WOFF2 directory

### ISSUE THREAD

**Issue by AndersonTorres** [crozynski/comicneue#22]
The title is self-explaining.

I found this bug(?) while updating the Nix package for comicneue.

**Comment by mshaw42** [comment]
The file naming is actually all over the place, 'where do I begin' when it comes to the 2.5 zip download.
The confusion is not helped by the abundance of Apple 'dot' files making the nest of folders double, which is no good if you just want the fonts.
The fonts in untold sub directories doesn't help, in fact it makes it easier for naming to go wrong.
The folders are also inconsistently named compared to the demo files. You want to extract it and the demo css file just work, with no renaming of 'WebFonts' to fonts to get started.
There is a mix up of 'oblique' and 'italic' going on. As mentioned, utterly no consistency.
Frequently I quickly use an online service to get a TTF font to something I can use online. https://transfonter.org/ works for me every time including in this instance. I was able to just upload the files and then get a neat list of files:

`@font-face {
    font-family: 'Comic Neue';
    src: url('fonts/ComicNeue-Bold.eot');
    src: local('Comic Neue Bold'), local('ComicNeue-Bold'),
        url('fonts/ComicNeue-Bold.eot?#iefix') format('embedded-opentype'),
        url('fonts/ComicNeue-Bold.woff2') format('woff2'),
        url('fonts/ComicNeue-Bold.woff') format('woff');
    font-weight: bold;
    font-style: normal;
    font-display: swap;
}

@font-face {
    font-family: 'Comic Neue';
    src: url('fonts/ComicNeue-LightItalic.eot');
    src: local('Comic Neue Light Italic'), local('ComicNeue-LightItalic'),
        url('fonts/ComicNeue-LightItalic.eot?#iefix') format('embedded-opentype'),
        url('fonts/ComicNeue-LightItalic.woff2') format('woff2'),
        url('fonts/ComicNeue-LightItalic.woff') format('woff');
    font-weight: 300;
    font-style: italic;
    font-display: swap;
}

@font-face {
    font-family: 'Comic Neue';
    src: url('fonts/ComicNeue-Regular.eot');
    src: local('Comic Neue Regular'), local('ComicNeue-Regular'),
        url('fonts/ComicNeue-Regular.eot?#iefix') format('embedded-opentype'),
        url('fonts/ComicNeue-Regular.woff2') format('woff2'),
        url('fonts/ComicNeue-Regular.woff') format('woff');
    font-weight: normal;
    font-style: normal;
    font-display: swap;
}

@font-face {
    font-family: 'Comic Neue';
    src: url('fonts/ComicNeue-BoldItalic.eot');
    src: local('Comic Neue Bold Italic'), local('ComicNeue-BoldItalic'),
        url('fonts/ComicNeue-BoldItalic.eot?#iefix') format('embedded-opentype'),
        url('fonts/ComicNeue-BoldItalic.woff2') format('woff2'),
        url('fonts/ComicNeue-BoldItalic.woff') format('woff');
    font-weight: bold;
    font-style: italic;
    font-display: swap;
}

@font-face {
    font-family: 'Comic Neue';
    src: url('fonts/ComicNeue-Italic.eot');
    src: local('Comic Neue Italic'), local('ComicNeue-Italic'),
        url('fonts/ComicNeue-Italic.eot?#iefix') format('embedded-opentype'),
        url('fonts/ComicNeue-Italic.woff2') format('woff2'),
        url('fonts/ComicNeue-Italic.woff') format('woff');
    font-weight: normal;
    font-style: italic;
    font-display: swap;
}

@font-face {
    font-family: 'Comic Neue';
    src: url('fonts/ComicNeue-Light.eot');
    src: local('Comic Neue Light'), local('ComicNeue-Light'),
        url('fonts/ComicNeue-Light.eot?#iefix') format('embedded-opentype'),
        url('fonts/ComicNeue-Light.woff2') format('woff2'),
        url('fonts/ComicNeue-Light.woff') format('woff');
    font-weight: 300;
    font-style: normal;
    font-display: swap;
}

@font-face {
    font-family: 'Comic Neue Angular';
    src: url('fonts/ComicNeueAngular-BoldItalic.eot');
    src: local('Comic Neue Angular Bold Italic'), local('ComicNeueAngular-BoldItalic'),
        url('fonts/ComicNeueAngular-BoldItalic.eot?#iefix') format('embedded-opentype'),
        url('fonts/ComicNeueAngular-BoldItalic.woff2') format('woff2'),
        url('fonts/ComicNeueAngular-BoldItalic.woff') format('woff');
    font-weight: bold;
    font-style: italic;
    font-display: swap;
}

@font-face {
    font-family: 'Comic Neue Angular';
    src: url('fonts/ComicNeueAngular-Bold.eot');
    src: local('Comic Neue Angular Bold'), local('ComicNeueAngular-Bold'),
        url('fonts/ComicNeueAngular-Bold.eot?#iefix') format('embedded-opentype'),
        url('fonts/ComicNeueAngular-Bold.woff2') format('woff2'),
        url('fonts/ComicNeueAngular-Bold.woff') format('woff');
    font-weight: bold;
    font-style: normal;
    font-display: swap;
}

@font-face {
    font-family: 'Comic Neue Angular';
    src: url('fonts/ComicNeueAngular-Light.eot');
    src: local('Comic Neue Angular Light'), local('ComicNeueAngular-Light'),
        url('fonts/ComicNeueAngular-Light.eot?#iefix') format('embedded-opentype'),
        url('fonts/ComicNeueAngular-Light.woff2') format('woff2'),
        url('fonts/ComicNeueAngular-Light.woff') format('woff');
    font-weight: 300;
    font-style: normal;
    font-display: swap;
}

@font-face {
    font-family: 'Comic Neue Angular';
    src: url('fonts/ComicNeueAngular-Italic.eot');
    src: local('Comic Neue Angular Italic'), local('ComicNeueAngular-Italic'),
        url('fonts/ComicNeueAngular-Italic.eot?#iefix') format('embedded-opentype'),
        url('fonts/ComicNeueAngular-Italic.woff2') format('woff2'),
        url('fonts/ComicNeueAngular-Italic.woff') format('woff');
    font-weight: normal;
    font-style: italic;
    font-display: swap;
}

@font-face {
    font-family: 'Comic Neue Angular';
    src: url('fonts/ComicNeueAngular-Regular.eot');
    src: local('Comic Neue Angular Regular'), local('ComicNeueAngular-Regular'),
        url('fonts/ComicNeueAngular-Regular.eot?#iefix') format('embedded-opentype'),
        url('fonts/ComicNeueAngular-Regular.woff2') format('woff2'),
        url('fonts/ComicNeueAngular-Regular.woff') format('woff');
    font-weight: normal;
    font-style: normal;
    font-display: swap;
}

@font-face {
    font-family: 'Comic Neue Angular';
    src: url('fonts/ComicNeueAngular-LightItalic.eot');
    src: local('Comic Neue Angular Light Italic'), local('ComicNeueAngular-LightItalic'),
        url('fonts/ComicNeueAngular-LightItalic.eot?#iefix') format('embedded-opentype'),
        url('fonts/ComicNeueAngular-LightItalic.woff2') format('woff2'),
        url('fonts/ComicNeueAngular-LightItalic.woff') format('woff');
    font-weight: 300;
    font-style: italic;
    font-display: swap;
}
`

I am good with this, it just works. No need to do lots of renaming, no OSX resource fork weird files, just a fonts folder with the goodies I need for the web.

**Comment by crozynski** [comment]
Hi @AndersonTorres @mshaw42 

These issues should now be fixed: https://github.com/crozynski/comicneue/releases/tag/2.51

The changes that I've merged are:

– Improved web font file organisation
– Simpler directory structure.
– Removed references to Oblique.
– Removed support for EOT.
– Updated CSS.
– Included transfonter.org's demo.html.

When I used the Mac command to reveal hidden files nothing appeared in the Webfonts directory. If you're seeing anything that shouldn't be there please let me know and I'll try and remove them.

Thanks for using the font.

Craig Rozynski
