### ISSUE TITLE
Website has wrong certificate for HTTPS

### ISSUE THREAD

**Issue by pinobatch** [crozynski/comicneue#6]
Accessing <https://comicneue.com/> in Firefox gives an error that the certificate is valid only for `www.sf.craigrozynski.com`.

One of two solutions may work:

* Obtain a TLS certificate with subject alternate names for `comicneue.com` and `www.comicneue.com`, and use Server Name Indication (SNI) to serve it whenever one of those domains is accessed.
* Obtain a TLS certificate with subject alternate names for all domains handled by the server (at least `comicneue.com`, `www.comicneue.com`, and `www.sf.craigrozynski.com`), and use that.

The Let's Encrypt certificate authority offers 90-day certificates at no charge, and Electronic Frontier Foundation offers a free tool called [Certbot] to automate issuance, installation, and renewal of certificates from Let's Encrypt.

[Certbot]: https://github.com/certbot/certbot

**Comment by crozynski** [comment]
Thanks @pinobatch.

There is no intention for SSL to be applied to comicneue.com. The browser is correct in stating that the site is not secure. It's unfortunate that it says it hasn't been configured properly, as there is a valid certificate for sf.craigrozynski.com, which is intentional.
