### ISSUE TITLE
please tag releases

### ISSUE THREAD

**Issue by jonasstein** [crozynski/comicneue#8]
Thank you for the font. We distribute it on Gentoo Linux. You could help us to keep track, by tagging commits with semantic version numbers.
https://github.com/crozynski/comicneue/releases
http://semver.org/

http://comicneue.com/ writes about 2.3 and 2.2 here I saw just a comment about 2.1.
other distributions with your fonts:
https://repology.org/metapackage/fonts:comic-neue/versions

**Comment by crozynski** [comment]
Okay thanks @jonasstein. I'll use the major.minor.patch versioning to tag future commits. Did you want to tag past releases retrospectively? That seems a little less straightforward.

**Comment by kilobyte** [comment]
There's only four non-merge commits in the repository, of those three look like they correspond to versions (2.1, 2.2, 2.3) — so this looks obvious to me.

All that I (as Debian packager) really care for, though, is a tag for the current version; I assume Gentoos think similar.  Thus, historic releases might be nice but don't matter for my particular use case.

**Comment by jonasstein** [comment]
@crozynski that is great. It is fine, if you use 2.1, 2.2... 
Important is to have a tagged release, because the maintainers have to search through the files else and this is devastating. Some tools can even alert maintainers, if there is a new tagged version. This is not possible, if there are no tags. Tagging the old ones (2.1, ... ) is done very quickly, so I would say it is worth it.
In the idea of Gentoo it is up to the user to select the version, if possible. While debian has one testing version, you can select on Gentoo sometimes between many.

**Comment by crozynski** [comment]
Okay thanks @jonasstein and @kilobyte.
I'm not proficient with git in terminal so I'll run through what I've just done:
1. Added version tags to each past release locally with `git tag -a v2.X XXXXX`
2. `git commit`
3. `git push`
As there are 5 commits the latest version is now 2.4 (2.0 through to 2.4). Please let me know if you can't see the tags. I note here https://github.com/crozynski/comicneue/tags there are still no tags being displayed.

**Comment by jonasstein** [comment]
You need either `git push origin --tags` see: https://git-scm.com/book/en/v2/Git-Basics-Tagging 
or you tag by mouse in the github website. Copy and paste your commit ID where the position says `master` per default.
